#!/bin/sh

# snippets

ph=XXX

lang=shell
while getopts :l: args; do case $args in
	(l) lang="$OPTARG" ;;
	(*) ;;
esac; done

while read -r key; do
case $lang in

	(html)
	case $key in
		(main|init)
			printf '<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>%s</title>
	<link rel="stylesheet" href="style.css">
</head>
<body>

	<header><h1>%s</h1></header>
	<p>%s</p>

</body>
</html>
' $ph $ph $ph
	esac
	;;

	(md|zk|markdown|zettelkasten) # ------------------------------------------
	case $key in

		(init)
			printf -- "---\ndate: $(date +%Y-%m-%dT%H:%M)\n---\n\n# ";;

		(*) ;;
	esac
	;;

	(rust|rs) # --------------------------------------------------------------
	case $key in

		(main|init)
			printf 'fn main() {\n\n    println!("%s");\n\n}' $ph;;

		(*) ;;
	esac
	;;

	(shell|sh) # -------------------------------------------------------------
	case $key in

		(f|fi|fil|file*)
			printf "if [ -n \"\$1\" ]; then
	echo \"\$@\"
else
	while read -r filename; do
		echo \"\$filename\"
	done
fi";;

		(u|us|usg|usage)
			printf "#!/bin/sh

usage() {
	commandline=\"\$(basename \"\$0\") [ FILE(S) (or from stdin) ]\"
	>&2 printf \"usage:\\\n\\\t\\\033[33m%%s\\\033[0m\\\n\" \"\$commandline\";
}

case \$1 in
	(-h|--help) usage; exit 0;;
	(*) usage; exit 1;;
esac
";;

		(c|ca|cas|case)
			printf "case \$key in
	(hello) printf 'hello';;
	(*) printf 'default';;
esac
";;

		(i|in|ini|init)
			printf "#!/bin/sh

usage() {
	commandline='commandline <usage> --like --this'
	>&2 printf \"usage:\\\n\\\t\\\033[33m\$commandline\\\033[0m\\\n\";
}

case \$1 in
	(-h|--help) usage; exit 0;;
	(*) usage; exit 1;;
esac
";;

		(stdin)
			printf 'while read -r line; do\n\techo "$line";\ndone;\n';;

		(*) ;;
	esac
	;;


	(c) # --------------------------------------------------------------------
	case $key in

		(init)
			printf "#include <stdio.h>\n\nint\nmain(int argc, char** argv)\n{\n\treturn 0;\n}\n";;

		(*) ;;
	esac
	;;


	(cc|c++|cpp) # -----------------------------------------------------------
	case $key in

		(init)
			printf "#include <iostream>\n\nint\nmain(int argc, char** argv)\n{\n\n\tstd::cout << \"%s\" << std::endl;\n\n\treturn 0;\n\n}\n" "$ph";;

		(*) ;;
	esac
	;;


	(make|mk) # --------------------------------------------------------------
	case $key in

		(init)
			printf "default:\n\tcc -o main main.c\n";;

		(*) ;;
	esac
	;;

	(python|py) # ------------------------------------------------------------
	case $key in

		(main|init)
			printf "if __name__ == '__main__':\n\n\tprint('%s')\n\n" $ph;;

		(nixinit)
			printf "#!/usr/bin/env nix-shell\n#!nix-shell -i python3 -p python38Packages.%s python38Packages.%s\n# vim:set ft=python:\n\n" "$ph" "$ph";;

		(*) ;;
	esac
	;;

esac
done
