#!/bin/sh

# snippets

ph=XXX

lang=shell
while getopts :l: args; do case $args in
	(l) lang="$OPTARG" ;;
	(*) ;;
esac; done

while read -r key; do
case $lang in

	(rust|rs) # --------------------------------------------------------------
	case $key in

		(main)
			printf 'fn main() {\n\n\tprintln!("%s");\n\n}' $ph;;

		(*) ;;
	esac
	;;

	(shell|sh) # -------------------------------------------------------------
	case $key in

		(init)
			printf "#!/bin/sh

# deps: usage

title='%s'
desc='%s'
args='%s'
opts='%s'
usg() { usage \"\$title - \$desc\" \"\$title \$args\" \"\$opts\"; }

while getopts :h args; do case \$args in
	(h) usg; exit 0 ;;
	([?]) usg; exit 2 ;;
esac; done

" $ph $ph $ph $ph;;

		(stdin)
			printf 'while read -r line; do\n\techo "$line";\ndone;\n';;

		(*) ;;
	esac
	;;


	(c) # --------------------------------------------------------------------
	case $key in

		(init)
			printf "#include <stdio.h>\n\nint main(int argc, char** argv) {\n\n\tprintf(\"%s\");\n\n\treturn 0;\n\n}\n" "$ph";;

		(*) ;;
	esac
	;;


	(cc|c++|cpp) # -----------------------------------------------------------
	case $key in

		(init)
			printf "#include <iostream>\n\nint main(int argc, char** argv) {\n\n\tstd::cout << \"%s\" << std::endl;\n\n\treturn 0;\n\n}\n" "$ph";;

		(*) ;;
	esac
	;;


	(make|mk) # --------------------------------------------------------------
	case $key in

		(init)
			printf "default:\n\tcc -o main main.c\n";;

		(*) ;;
	esac
	;;

	(python|py) # ------------------------------------------------------------
	case $key in

		(main)
			printf "if __name__ == '__main__':\n\n\tprint('%s')\n\n" $ph;;

		(nixinit)
			printf "#!/usr/bin/env nix-shell\n#!nix-shell -i python3 -p python38Packages.%s python38Packages.%s\n# vim:set ft=python:\n\n" "$ph" "$ph";;

		(*) ;;
	esac
	;;

esac
done
